channels:
  - conda-forge
  - ioam/label/dev
  - defaults

dependencies:
  - python
  - holoviews>=1.7dev2
  - numpy==1.13.1
  - pandas==0.20.3
  - scikit-learn==0.19.0
  - xarray==0.10.0
  - ipywidgets==7.0.0
  - geopandas==0.3.0