channels:
  - conda-forge
  - ioam/label/dev
  - defaults

dependencies:
  - xarray==0.10.0
  - python
  - holoviews==1.9.2
  - numpy==1.13.1
  - pandas==0.20.3
  - geopandas==0.3.0
  - bokeh==0.12.13
  - ipython==6.1.0
  - ipywidgets==7.0.0